apiVersion: apps/v1
kind: Deployment
metadata:
  name: "echo"
  labels:
    app.kubernetes.io/instance: "bookmarks-app"
    app.kubernetes.io/component: "echo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: "bookmarks-app"
      app.kubernetes.io/component: "echo"
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "bookmarks-app"
        app.kubernetes.io/component: "echo"
    spec:
      containers:
        - name: "echo"
          image: "inanimate/echo-server"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: "echo"
  labels:
    app.kubernetes.io/instance: "bookmarks-app"
    app.kubernetes.io/component: "echo"
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/instance: "bookmarks-app"
    app.kubernetes.io/component: "echo"
