apiVersion: apps/v1
kind: Deployment
metadata:
  name: "puppeteer"
  labels:
    app.kubernetes.io/instance: "bookmarks-app"
    app.kubernetes.io/component: "puppeteer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: "bookmarks-app"
      app.kubernetes.io/component: "puppeteer"
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "bookmarks-app"
        app.kubernetes.io/component: "puppeteer"
    spec:
      containers:
        - name: "puppeteer"
          image: "kpatel20538/bookmarks-app:puppeteer"
          env:
            - name: MINIO_ACCESS_KEY
              value: "minio-access-key"
            - name: MINIO_SECRET_KEY
              value: "minio-secret-key"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: "puppeteer"
  labels:
    app.kubernetes.io/instance: "bookmarks-app"
    app.kubernetes.io/component: "puppeteer"
spec:
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/instance: "bookmarks-app"
    app.kubernetes.io/component: "puppeteer"
